language: python
sudo: false

python:
  - 2.7
  - 3.4
  - 3.5
  - nightly
  - pypy
  - pypy3

matrix:
    allow_failures:
        - python: 2.7
        - python: nightly
        - python: pypy
        - python: pypy3

install:
    - "pip install -U pip"
    - "pip install -U pytest pytest-runner flake8 mypy-lang"
    - "pip install ."
    - "pip freeze"

script:
    - python setup.py test
    - python setup.py flake8 || true
    - mypy everywhere

notifications:
    email: false
